apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y7zee2pzx-go 
  janus-idp.io/tekton: y7zee2pzx-go
  backstage.io/kubernetes-id: y7zee2pzx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y7zee2pzx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  