apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y7zee2pzx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y7zee2pzx-go 
  name: y7zee2pzx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y7zee2pzx-go 
